server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: stack-overflow
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVER:localhost}:${POSTGRES_PORT:5411}/${POSTGRES_DATABASE:stack_overflow_postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres123}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: ${POSTGRES_DDL_AUTO:create}
    show-sql: ${POSTGRES_SHOW_SQL:true}

jwt:
  secret:
    key: abrakadabra
  expiration:
    hours: 10

springdoc:
  api-docs:
    path: /docs/v3/api-docs
  swagger-ui:
    path: /docs/swagger-ui/index.html
